/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PokedexImport } from './routes/pokedex'
import { Route as DetailPokemonImport } from './routes/$detailPokemon'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PokedexRoute = PokedexImport.update({
  path: '/pokedex',
  getParentRoute: () => rootRoute,
} as any)

const DetailPokemonRoute = DetailPokemonImport.update({
  path: '/$detailPokemon',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$detailPokemon': {
      id: '/$detailPokemon'
      path: '/$detailPokemon'
      fullPath: '/$detailPokemon'
      preLoaderRoute: typeof DetailPokemonImport
      parentRoute: typeof rootRoute
    }
    '/pokedex': {
      id: '/pokedex'
      path: '/pokedex'
      fullPath: '/pokedex'
      preLoaderRoute: typeof PokedexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$detailPokemon': typeof DetailPokemonRoute
  '/pokedex': typeof PokedexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$detailPokemon': typeof DetailPokemonRoute
  '/pokedex': typeof PokedexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$detailPokemon': typeof DetailPokemonRoute
  '/pokedex': typeof PokedexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$detailPokemon' | '/pokedex'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$detailPokemon' | '/pokedex'
  id: '__root__' | '/' | '/$detailPokemon' | '/pokedex'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DetailPokemonRoute: typeof DetailPokemonRoute
  PokedexRoute: typeof PokedexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetailPokemonRoute: DetailPokemonRoute,
  PokedexRoute: PokedexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$detailPokemon",
        "/pokedex"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$detailPokemon": {
      "filePath": "$detailPokemon.tsx"
    },
    "/pokedex": {
      "filePath": "pokedex.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
